---
version: "3"
silent: true

vars:
  GOPATH_BIN:
    sh: echo "$(go env GOPATH)/bin"

env:
  GOBIN: "{{.GOPATH_BIN }}"

tasks:
  lint:
    desc: "Run static analysis and code linting using golangci-lint"
    deps:
      - install
    cmds:
      - golangci-lint run --timeout 3m

  fmt:
    desc: "Formats all Go source files"
    cmds:
      - go fmt ./...

  vet:
    desc: "Examines Go source code and reports suspicious constructs"
    cmds:
      - go vet ./...

  test:
    desc: "Runs all tests in the project"
    aliases:
      - tests
    deps:
      - vet
    cmds:
      - go test ./...

  security:
    desc: "Run security vulnerability scan"
    deps:
      - install
    cmds:
      - govulncheck ./...

  install:
    desc: "Install required tools and dependencies"
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - test -f {{.GOPATH_BIN}}/govulncheck
      - test -f {{.GOPATH_BIN}}/golangci-lint

  all:
    desc: "Run comprehensive checks: format, lint, security and test"
    cmds:
      - task fmt
      - task lint
      - task vet
      - task security
      - task test
